name: CI/CD Frontend Dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Angular compatible et stable

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Deploy to test environment
        if: github.ref == 'refs/heads/dev'
        run: echo "🚀 Déploiement automatique frontend sur l'environnement dev"

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: |
            ${{ job.status == 'success' && '✅ Frontend build succeeded on dev' || '❌ Frontend build failed on dev' }}
          body: |
            Bonjour l'équipe Anilaye 👋,

            Le build Angular 19 sur la branche *dev* a terminé avec le statut : **${{ job.status }}**.

            📌 Repository: ${{ github.repository }}
            📌 Branch: ${{ github.ref }}
            📌 Commit: ${{ github.sha }}
            🔗 Lien: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}

            --
            GitHub Actions 🚀
          to: arona010ndiaye@gmail.com,aichasy2188@gmail.com,takkinoyaya@gmail.com,nguiranebabacar305@gmail.com,maladongom104@gmail.com
          from: "Team Edacy Groupe 30 <${{ secrets.EMAIL }}>"
