name: CI / CD Frontend Dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Build Angular project
        run: npm run build -- --prod
        working-directory: .

      - name: Run Angular tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: .

      - name: Deploy to test environment
        if: github.ref == 'refs/heads/dev'
        run: echo "Déploiement automatique frontend sur l'environnement dev"
